# Project-wide Gradle settings.
# http://www.gradle.org/docs/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure to make it clearer which packages are part of the Android SDK,
# and which are development libraries developed by the Android team via AndroidX.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Use local Java 17 for builds
# org.gradle.java.home=E:\\java17-microsoft
